backend:
  name: git-gateway
  branch: main # Change to 'master' if your GitHub uses that instead

media_folder: "images"
public_folder: "/images"

collections:
  - name: "archive"
    label: "Archive"
    folder: "archive" # This is just a placeholder for the CMS structure
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
